-- +migrate Up
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS country TEXT NOT NULL DEFAULT '';
ALTER TABLE node_metrics ADD COLUMN IF NOT EXISTS cpu_limit_pct DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE node_metrics ADD COLUMN IF NOT EXISTS ram_limit_mb BIGINT NOT NULL DEFAULT 0;
ALTER TABLE node_metrics ADD COLUMN IF NOT EXISTS battery_pct INT;
ALTER TABLE node_metrics ADD COLUMN IF NOT EXISTS charging BOOLEAN;
ALTER TABLE node_metrics ADD COLUMN IF NOT EXISTS network_type TEXT NOT NULL DEFAULT '';
